In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv(r"D:\geethanjaliexternship\source files\loan_data.csv")

In [3]:
dataset.head()

credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   
4              1         credit_card    0.1426       102.92       11.299732   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1               0   
1  14.29   707        2760.000000      33623        76.7               0   
2  11.63   682        4710.000000       3511        25.6               1   
3   8.10   712        2699.958333      33667        73.2               1   
4  14.97   667        4066.000000       4740        39.5               0   

   delinq.2yrs  pub.rec  not.fully.paid  
0            0        0               0  
1            0        0               0  
2            0        0               0  
3            0        0               0  
4            1        0               0

In [4]:
dataset.isnull().any()

credit.policy        False
purpose              False
int.rate             False
installment          False
log.annual.inc       False
dti                  False
fico                 False
days.with.cr.line    False
revol.bal            False
revol.util           False
inq.last.6mths       False
delinq.2yrs          False
pub.rec              False
not.fully.paid       False
dtype: bool

In [7]:
x = dataset.iloc[:,2:13].values
y = dataset.iloc[:,13].values

In [8]:
x

array([[1.18900000e-01, 8.29100000e+02, 1.13504065e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.07100000e-01, 2.28220000e+02, 1.10821426e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.35700000e-01, 3.66860000e+02, 1.03734912e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.07100000e-01, 9.78100000e+01, 1.05966347e+01, ...,
        8.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.60000000e-01, 3.51580000e+02, 1.08197783e+01, ...,
        5.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.39200000e-01, 8.53430000e+02, 1.12644641e+01, ...,
        6.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [9]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y ,test_size = 0.2, random_state= 0)

In [13]:
x_train.shape

(7662, 11)

In [14]:
x_test.shape

(1916, 11)

In [15]:
y_train.shape

(7662,)

In [16]:
y_test.shape

(1916,)

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
 
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [19]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense

In [20]:
bnn = Sequential()

In [21]:
bnn.add(Dense(11,kernel_initializer = "random_uniform" , activation = "relu"))

In [22]:
bnn.add(Dense(22,kernel_initializer = "random_uniform" , activation = "relu"))

In [24]:
bnn.add(Dense(1,kernel_initializer = "random_uniform" , activation = "sigmoid"))

In [25]:
bnn.compile("adam" , "binary_crossentropy" , metrics = ["accuracy"])

In [26]:
bnn.fit(x_train,y_train, batch_size = 32 , epochs = 100)

Epoch 1/100
240/240 [==============================] - 2s 2ms/step - loss: 0.5962 - accuracy: 0.8325
Epoch 2/100
240/240 [==============================] - 1s 2ms/step - loss: 0.4255 - accuracy: 0.8359
Epoch 3/100
240/240 [==============================] - 1s 2ms/step - loss: 0.4099 - accuracy: 0.8432
Epoch 4/100
240/240 [==============================] - 1s 2ms/step - loss: 0.4071 - accuracy: 0.8428
Epoch 5/100
240/240 [==============================] - 1s 2ms/step - loss: 0.4108 - accuracy: 0.8430
Epoch 6/100
240/240 [==============================] - 1s 2ms/step - loss: 0.4108 - accuracy: 0.8427
Epoch 7/100
240/240 [==============================] - 1s 2ms/step - loss: 0.4150 - accuracy: 0.8396
Epoch 8/100
240/240 [==============================] - 1s 2ms/step - loss: 0.4029 - accuracy: 0.8433
Epoch 9/100
240/240 [==============================] - 1s 2ms/step - loss: 0.4112 - accuracy: 0.8418
Epoch 10/100
240/240 [==============================] - 1s 2ms/step - loss: 0.4248 - accura

240/240 [==============================] - 1s 2ms/step - loss: 0.4056 - accuracy: 0.8430
Epoch 82/100
240/240 [==============================] - 1s 2ms/step - loss: 0.4124 - accuracy: 0.8411
Epoch 83/100
240/240 [==============================] - 1s 2ms/step - loss: 0.4092 - accuracy: 0.8411
Epoch 84/100
240/240 [==============================] - 1s 2ms/step - loss: 0.4081 - accuracy: 0.8410
Epoch 85/100
240/240 [==============================] - 1s 2ms/step - loss: 0.4020 - accuracy: 0.8436
Epoch 86/100
240/240 [==============================] - 1s 2ms/step - loss: 0.3996 - accuracy: 0.8483
Epoch 87/100
240/240 [==============================] - 1s 2ms/step - loss: 0.3915 - accuracy: 0.8499
Epoch 88/100
240/240 [==============================] - 1s 2ms/step - loss: 0.4061 - accuracy: 0.8411
Epoch 89/100
240/240 [==============================] - 1s 2ms/step - loss: 0.3995 - accuracy: 0.8457
Epoch 90/100
240/240 [==============================] - 1s 2ms/step - loss: 0.4148 - accuracy: 

In [27]:
ypred = bnn.predict(x_test)

In [30]:
ypred<0.5

array([[ True],
       [ True],
       [ True],
       ...,
       [ True],
       [ True],
       [ True]])

In [31]:
y_test<0.5

array([ True,  True,  True, ...,  True, False,  True])

In [32]:
dataset.head(1)

credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189        829.1       11.350407   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1               0   

   delinq.2yrs  pub.rec  not.fully.paid  
0            0        0               0

In [33]:
yp = bnn.predict_classes(sc.transform([[0.122,12.1,11.11,12.2,532,1234.432,12567,33.2,1,1,0]]))

C:\Users\heart\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [34]:
yp

array([[0]])