In [2]:
import numpy as np
import pandas as pd


In [3]:
dataset = pd.read_csv(r"D:\geethanjaliexternship\source files\Annual_growth.csv")

In [4]:
dataset.head(10
            )

Growth  Log_size Species Patch_type Landscape
0   6.628041  5.375278      CB  Connected        10
1   7.038784  5.472271      CB  Connected        10
2  11.032047  6.879356      CB  Connected        10
3   6.908755  5.310740      CB  Connected        10
4   9.202308  4.985317      CB  Connected        10
5   6.739337  4.916325      CB  Connected        10
6   6.659294  5.496143      CB  Connected        10
7   5.886104  4.007333      CB  Connected        10
8   7.049255  4.412798      CB  Connected        10
9   5.030438  3.912023      CB  Connected        10

In [5]:
dataset.isnull().any()

Growth        False
Log_size      False
Species       False
Patch_type    False
Landscape     False
dtype: bool

In [6]:
dataset["Patch_type"].unique()

array(['Connected', 'Rectangular', 'Winged'], dtype=object)

In [7]:
dataset["Species"].unique()

array(['CB', 'LE'], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

dataset["Species"] = le.fit_transform(dataset["Species"])
dataset["Landscape"] = le.fit_transform(dataset["Landscape"])
dataset["Patch_type"] = le.fit_transform(dataset["Patch_type"])

In [9]:
dataset["Landscape"].unique()

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [10]:
x = dataset.iloc[:,[0,1,3,4]].values
y = dataset.iloc[:,3].values

In [11]:
x

array([[ 6.62804138,  5.37527841,  0.        ,  0.        ],
       [ 7.03878354,  5.47227067,  0.        ,  0.        ],
       [11.03204692,  6.8793558 ,  0.        ,  0.        ],
       ...,
       [ 6.03188646,  4.50810847,  2.        ,  7.        ],
       [ 5.64721212,  4.09434456,  0.        ,  7.        ],
       [ 8.57395153,  5.768321  ,  2.        ,  7.        ]])

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 0, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       2, 2, 0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 0, 0, 1, 0, 2, 2, 1, 1, 1,
       1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2,
       2, 1, 1, 0, 2, 0, 0, 1, 0, 2, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 2, 2, 0, 0, 0, 1, 0, 0, 2, 1, 2, 0, 1, 2, 2, 0,
       0, 0, 0, 1, 0, 0, 1, 2, 1, 1, 0, 1, 0, 2, 0, 0, 1, 1, 1, 0, 0, 2,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 2, 0, 0, 0, 0, 1, 1, 2, 2, 0, 1, 1,
       0, 0, 1, 1, 0, 2, 2, 1, 0, 1, 2, 1, 2, 1, 2, 2, 1, 0, 2, 0, 2, 1,
       1, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 2, 1, 2, 1, 2, 0, 2, 0,
       0, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2,
       2, 0, 2, 0, 2, 1, 2, 1, 2, 0, 0, 0, 2, 1, 1, 0, 2, 0, 0, 2, 0, 0,
       2, 2, 0, 0, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer([("oh" , OneHotEncoder(),[2,3])],remainder = "passthrough")
x = ct.fit_transform(x)


C:\Users\heart\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer([("oh" , OneHotEncoder(),[0])],remainder = "passthrough")
y = ct.fit_transform(y)



IndexError: tuple index out of range